# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
  pre_build:
    commands:
      - echo "[+] Running pre-build tasks"
      - ECR_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - FUNCTION_NAMES="${SYSTEM_NAME}_${ENV}_CommandFunction ${SYSTEM_NAME}_${ENV}_ProcessSQSFunction ${SYSTEM_NAME}_${ENV}_ProcessStreamFunction ${SYSTEM_NAME}_${ENV}_AuthFunction ${SYSTEM_NAME}_${ENV}_QueryFunction ${SYSTEM_NAME}_${ENV}_WaitSQSConsumerFunction"
      - REPO_NAME="${SYSTEM_NAME}_${ENV}_repository"
      - aws --version
      # login to ECR
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}

      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - echo $IMAGE_TAG
  build:
    commands:
      - echo "[+] building ...."
      - docker build --pull -t $ECR_URI/$REPO_NAME:$LATEST_DOCKER_TAG .
      - docker tag $ECR_URI/$REPO_NAME:$LATEST_DOCKER_TAG $ECR_URI/$REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "SAM packaging completed on `date`"

      - docker push $ECR_URI/$REPO_NAME:$IMAGE_TAG
      - docker push $ECR_URI/$REPO_NAME:$LATEST_DOCKER_TAG
      - echo "Pushed $ECR_URI/$REPO_NAME:$IMAGE_TAG"
      - echo "Pushed $ECR_URI/$REPO_NAME:$LATEST_DOCKER_TAG"
      - for FUNCTION_NAME in $(echo $FUNCTION_NAMES | sed "s/ / /g"); do
        aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $ECR_URI/$REPO_NAME:$LATEST_TAG;
        done
